SEED: 1510
DEFALT_PROB_IMITATION: 0.2
EXPERIENCE_BUFFER_SIZE: 1000

gpu_id: 0
gamma: .95

max_episode_length: 1000

# Path: model.yml
PATH:
  ref_path_file: "/home/bld/HK_RL/RLagents_v3/lMRP_paths"
  cbs_file: "/home/bld/HK_RL/RLagents_v3/libMultiRobotPlanning/build/cbs"

LOG:
  print_interval: 1
  log_path: "/home/bld/HK_RL/RLagents_v3/logs/"

batch_items: 32


entr_alpha: 0.01
max_episode_reward: 0

optimal:
  opt: 'adam' 
  lr : 0.0001 
  weight_decay : 0 
  momentum : 0.9 
  epochs : 1_000_000
  sched : 'cosine' 
  min_lr : 0.000001
  warmup_lr : 0.005 
  warmup_epochs : 200 
  cooldown_epochs : 500
  decay_epochs : [200, 500, 1000, 5000, 10_000, 20_000, 50_000, 100_000, 200_000, 500_000, 1_000_000]
  decay_rate : 0.5

SAVE:
  model: