python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log
python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log
python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log
python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log
python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log
python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log
python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log
python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log
python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log
python scripts_0.py --gpu_id=0 --map_size=20 --map_density=0.01 --imi_prob=0.8 --wandb_log