python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=10 --map_density=0.1 --imi_prob=0.2 --wandb_log