python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log
python scripts_0.py --gpu_id=1 --map_size=40 --map_density=0.01 --imi_prob=0.5 --wandb_log