observation: 
  type: "EnvWorld"

episode_limit: 20
map_generator: maze_generator
action: 
  type: "EnvAction"
num_agents: 2
observation_size: 10
DIAGONAL_MOVEMENT: False
SIZE: (5,5)
PROB: (0,0.1)
finished: False
#above are mapf need

simulation_frequency: 10
duration: 40  # [s]
ego_spacing: 2
vehicles_density: 1
            # The reward received when colliding with a vehicle.
collision_reward: -1
            # The reward received when driving on the right-most lanes, linearly mapped to
right_lane_reward: 0.1
            # zero for other lanes.
            # The reward received when driving at full speed, linearly mapped to zero for
high_speed_reward: 0.4
            # lower speeds according to config["reward_speed_range"].
reward_speed_range: [20, 30]
normalize_reward: True
offroad_terminal: False
ACTION_COST: -0.3
GOAL_REWARD: 5.
COLLISION_REWARD: -2
frozen_steps: 0
isOneShot: False
IsDiagonal: False
viewer: 